//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 產生的 Include 檔案。
// 由 game.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_RACKET                      131
#define IDB_BITMAP1                     132
#define IDB_BALL1                       134
#define IDB_BALL2                       135
#define IDB_BALL3                       136
#define IDB_BALL4                       137
#define IDB_0                           138
#define IDB_1                           139
#define IDB_100                         139
#define IDB_2                           140
#define IDB_3                           141
#define IDB_4                           142
#define IDB_5                           143
#define IDB_6                           144
#define IDB_7                           145
#define IDB_8                           146
#define IDB_9                           147
#define IDB_MINUS                       148
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_BITMAP2                     156
#define IDB_LOADING                     156
#define IDB_WEIBAITOWN                  166
#define IDB_BILLBOARD                   167
#define IDB_GRASS_LAND                  168
#define IDB_GREEN_FLOWER                169
#define IDB_GREEN_GRASS                 170
#define IDB_GREEN_TREE                  171
#define IDB_WEIBAITOWN_HOUSE1           172
#define IDB_WEIBAITOWN_HOUSE2           173
#define IDB_BITMAP10                    174
#define IDB_WEIBAITOWN_PRO_HOUSE        174
#define HERO_BACK                       176
#define HERO_BACK_ONE                   177
#define HERO_BACK_TWO                   178
#define HERO_FRONT                      179
#define HERO_FRONT_ONE                  180
#define HERO_FRONT_TWO                  181
#define HERO_LEFT                       182
#define IDB_BITMAP11                    183
#define HERO_LEFT_ONE                   183
#define HERO_RIGHT                      185
#define HERO_RIGHT_ONE                  186
#define HERO_RIGHT_TWO                  187
#define IDB_WEIBAITOWN_HOUSE1_1F        188
#define IDB_WEIBAITOWN_HOUSE2_1F        189
#define IDB_WEIBAITOWN_PRO_HOUSE_INSIDE 190
#define IDB_WEIBAITOWN_HOUSE1_2F        191
#define IDB_BITMAP4                     192
#define IDB_WEIBAITOWN_HOUSE2_2F        192
#define MOM_UP                          193
#define MOM_LEFT                        194
#define MOM_RIGHT                       195
#define HOME                            196
#define HOME_LOG                        197
#define MOM_DOWN                        198
#define NORMAL_DIALOG_SCREEN            199
#define TEXT_CURSOR2                    200
#define TEXT_CURSOR1                    201
#define TEXT_CURSOR3                    202
#define SYSTEM_DIALOG_SCREEN            203
#define IDB_BITMAP3                     204
#define HOME_LOG_BLANK                  204
#define IDB_ALPHABET_SMALL_A            205
#define IDB_ALPHABET_SMALL_B            206
#define IDB_ALPHABET_SMALL_C            207
#define IDB_ALPHABET_SMALL_D            208
#define IDB_ALPHABET_SMALL_E            210
#define IDB_ALPHABET_SMALL_F            211
#define IDB_ALPHABET_SMALL_G            212
#define IDB_ALPHABET_SMALL_H            213
#define IDB_ALPHABET_SMALL_I            214
#define IDB_ALPHABET_SMALL_J            215
#define IDB_TEXT_SPACE                  216
#define IDB_ALPHABET_SMALL_K            217
#define IDB_ALPHABET_SMALL_L            218
#define IDB_ALPHABET_SMALL_O            219
#define IDB_ALPHABET_SMALL_Q            220
#define IDB_ALPHABET_SMALL_S            221
#define IDB_ALPHABET_SMALL_M            222
#define IDB_ALPHABET_SMALL_T            223
#define IDB_ALPHABET_SMALL_V            224
#define IDB_ALPHABET_SMALL_W            225
#define IDB_ALPHABET_SMALL_X            227
#define IDB_ALPHABET_SMALL_N            228
#define IDB_ALPHABET_SMALL_P            229
#define IDB_ALPHABET_SMALL_R            230
#define IDB_ALPHABET_SMALL_U            231
#define IDB_ALPHABET_SMALL_Y            232
#define IDB_ALPHABET_SMALL_Z            233
#define IDB_JUMP_LAND                   234
#define HERO_LEFT_TWO                   235
#define FATGUY_LEFT                     237
#define FATGUY_RIGHT                    238
#define LITTLE_GIRL_FRONT               239
#define FATGUY_BACK                     240
#define FATGUY_UP                       240
#define IDB_BITMAP9                     241
#define FATGUY_FRONT                    241
#define FATGUY_DOWN                     241
#define IDB_BATTLE_BACKGROUND           242
#define IDB_BATTLE_GROUND               243
#define IDB_BATTLE_HERO                 244
#define IDB_BATTLE_OPTION               245
#define IDB_BLACK                       246
#define IDB_ENEMY_BAR                   247
#define IDB_HP_GREEN                    248
#define IDB_HP_RED                      249
#define IDB_HP_YELLOW                   250
#define IDB_MY_BAR                      251
#define IDB_SKILL_IMPACT1               252
#define IDB_SKILL_IMPACT2               253
#define IDB_SKILL_OPTION                254
#define IDB_PM_TREECKO_BACK             255
#define IDB_PM_TREECKO_FRONT            256
#define IDB_ATK_CURSOR                  257
#define IDB_BATTLE_DIALOG               258
#define IDB_BITMAP5                     259
#define IDB_M_GREEN_GRASS               259
#define IDB_ALPHABET_SPACE              260
#define IDB_ALPHABET_DOT                261
#define IDB                             261
#define IDB_ALPHABET_END                262
#define IDB_BITMAP6                     263
#define BG_BACKPACK                     263
#define IDB_PICKABLE_OBJECT             264
#define BG_SELF                         266
#define BG_BACKPACK_CURSOR1             267
#define BG_BACKPACK_CURSOR2             268
#define BG_BACKPACK_CURSOR3             269
#define BG_BACKPACK_FLAG                270
#define IDB_ANTIDOTE                    272
#define ITEM_ANTIDOTE                   272
#define BG_BACKPACK_ITEMCURSOR          273
#define BG_BACKPACK_BACK                274
#define IDB_MENU_BOTTOM                 275
#define IDB_MENU_MIDDLE                 276
#define IDB_MENU_TOP                    277
#define IDB_POKEMON_OPERATION_PANEL     278
#define IDB_POKEMON_BAR_UNSELECTED      279
#define IDB_POKEMON_BAR_FIRST_UNSELECTED 281
#define IDB_POKEMON_BAR_SELECTED        282
#define IDB_POKEMON_SELECT_PANEL        283
#define IDB_EXPBAR                      284
#define IDB_PM_ABILITY                  285
#define IDB_PM_SKILL_PANEL              286
#define IDB_POKEMON_BAR_FIRST_SELECT    287
#define IDB_POKEMON_BAR_SELECT          288
#define IDB_BITMAP7                     289
#define IDB_SKILL_SELECT                290
#define IDB_SKILL_SIDEBAR               291
#define IDB_BITMAP8                     292
#define IDB_SKILL_LIST                  292
#define BG_YESNO                        293
#define IDB_ICON_PM_TREECKO             294
#define BAG_PANEL                       295
#define BG_PANEL                        295
#define IDB_QU                          297
#define IDB_QUESTION_MARK               297
#define IDB_BITMAP12                    298
#define IDB_BITMAP13                    299
#define BG_ITEMAMOUNT                   299
#define IDB_BITMAP14                    300
#define IDB_BITMAP15                    301
#define IDB_HOSPITAL                    302
#define IDB_ALPHABET_DIVISION           303
#define IDB_NORMAL_HOUSE1               304
#define IDB_STORE                       305
#define IDB_LV_UP_PANEL                 306
#define IDB_LV_UP_FPANEL                307
#define IDB_HOSPITAL_INSIDE             308
#define HEAL_BALL1                      309
#define HEAL_BALL2                      310
#define HEAL_BALL3                      311
#define HEAL_BALL4                      312
#define HEAL_BALL5                      313
#define HEAL_BALL6                      314
#define HEAL_BALL7                      315
#define HEAL_BALL8                      316
#define HEAL_BALL9                      317
#define HEAL_BALL10                     318
#define HEAL_BALL11                     319
#define HEAL_BALL12                     320
#define IDB_ICON_PM_JIRACHI             321
#define IDB_PM_JIRACHI_BACK             322
#define IDB_PM_JIRACHI_FRONT            323
#define IDB_SKILL_LEER1                 324
#define IDB_SKILL_LEER2                 325
#define IDB_SKILL_LEER3                 326
#define IDB_SKILL_LEER4                 327
#define IDB_SKILL_LEER5                 328
#define IDB_GREEN_FLOWER2               329
#define IDB_GREEN_FLOWER3               330
#define IDB_PM_HOOH_BACK                331
#define IDB_PM_HOOH_FRONT               332
#define IDB_ICON_PM_HOOH                333
#define IDB_SKILL_EMBER1                334
#define IDB_SKILL_EMBER2                335
#define IDB_SKILL_EMBER3                336
#define IDB_SKILL_EMBER4                337
#define IDB_SKILL_EMBER5                338
#define IDB_SKILL_EMBER6                339
#define IDB_SKILL_EMBER7                340
#define IDB_SKILL_EMBER8                341
#define IDB_SKILL_EMBER9                342
#define IDB_SKILL_EMBER10               343
#define IDB_SKILL_EMBER11               344
#define IDB_SKILL_EMBER12               345
#define IDB_SKILL_EMBER13               346
#define IDB_SKILL_EMBER14               347
#define IDB_SKILL_EMBER15               348
#define IDB_SKILL_EMBER16               349
#define IDB_SKILL_EMBER17               350
#define IDB_SKILL_EMBER18               351
#define IDB_BITMAP17                    352
#define IDB_BURN_ICON                   352
#define IDB_CURSOR                      353
#define IDB_SHOP_MAP                    354
#define SHOP_BLANK_PANEL                355
#define SHOP_DESCRIPTION_PANEL          356
#define SHOP_IMAGE_PANEL                357
#define SHOP_ITEMLIST_PANEL             358
#define SHOP_MONEY_PANEL                359
#define TRADEMODE_SELECT                360
#define IDB_USEITEM_PANEL               361
#define IDB_BLANK_PANEL                 362
#define IDB_GIVEITEM_PANEL              363
#define ITEM_FIGHTERGLOVE               364
#define ITEM_VULNERARY                  365
#define IDB_USEONATK_PANEL              366
#define IDB_BITMAP19                    367
#define ITEM_POKEBALL                   367
#define IDB_ENEMY_SKILL_EMBER1          368
#define IDB_ENEMY_SKILL_EMBER2          369
#define IDB_ENEMY_SKILL_EMBER3          370
#define IDB_ENEMY_SKILL_EMBER4          371
#define IDB_ENEMY_SKILL_EMBER5          372
#define IDB_ENEMY_SKILL_EMBER6          373
#define IDB_ENEMY_SKILL_EMBER7          374
#define IDB_ENEMY_SKILL_EMBER8          375
#define IDB_ENEMY_SKILL_EMBER9          376
#define IDB_ENEMY_SKILL_EMBER10         377
#define IDB_ENEMY_SKILL_EMBER11         378
#define IDB_ENEMY_SKILL_EMBER12         379
#define IDB_ENEMY_SKILL_EMBER13         380
#define IDB_ENEMY_SKILL_EMBER14         381
#define IDB_ENEMY_SKILL_EMBER15         382
#define IDB_ENEMY_SKILL_EMBER16         383
#define IDB_ENEMY_SKILL_EMBER17         384
#define ITEM_BURNMEDICINE               385
#define IDB_MAY_ATK                     386
#define IDB_CATCH_BALL1                 387
#define IDB_CATCH_BALL2                 388
#define IDB_BITMAP21                    389
#define HOME5                           389
#define IDB_CATCH_BALL3                 390
#define HOME1                           391
#define HOME2                           392
#define HOME3                           393
#define HOME4                           394
#define HOME6                           396
#define HOME7                           397
#define POKEMON_MENU_ITEMCHOOSE         398
#define IDB_MAY_BACK                    399
#define IDB_MAY_FRONT                   401
#define IDB_MAY_LEFT                    402
#define IDB_MAY_RIGHT                   403
#define IDB_PMLIST_DEADBALL             404
#define IDB_PMLIST_LEFT                 405
#define IDB_PMLIST_LIVEBALL             406
#define IDB_PMLIST_RIGHT                407
#define IDB_PMLIST_NONEBALL             408
#define IDB_BITMAP16                    409
#define IDB_SHADOW                      409
#define HAVEITEM_ICON                   410
#define IDB_SHINE_GRASS1                411
#define IDB_SHINE_GRASS2                412
#define IDB_DOUCHITOWN_HOUSE1           413
#define IDB_DOUCHITOWNI_HOUSE2          414
#define IDB_PM_VULPIX_FRONT             414
#define IDB_PM_VAPOREON_FRONT           416
#define IDB_PM_SMOOCHUM_FRONT           417
#define IDB_PM_PIKACHU_FRONT            418
#define IDB_PM_METANG_FRONT             419
#define IDB_PM_GROVYLE_FRONT            420
#define IDB_PM_GRIMER_FRONT             421
#define IDB_PM_GARDEVOIR_FRONT          422
#define IDB_PM_RAYQUAZA_FRONT           423
#define IDB_PM_DEOXYS_BACK              424
#define IDB_PM_VULPIX_BACK              425
#define IDB_PM_VAPOREON_BACK            426
#define IDB_PM_SMOOCHUM_BACK            427
#define IDB_PM_PIKACHU_BACK             428
#define IDB_PM_METANG_BACK              429
#define IDB_PM_GROVYLE_BACK             430
#define IDB_PM_GRIMER_BACK              431
#define IDB_PM_GARDEVOIR_BACK           432
#define IDB_PM_RAYQUAZA_BACK            433
#define IDB_ICON_PM_VAPOREON            434
#define IDB_ICON_PM_PIKACHU             435
#define IDB_ICON_PM_METANG              436
#define IDB_ICON_PM_GROVYLE             437
#define IDB_ICON_PM_GRIMER              438
#define IDB_ICON_PM_GARDEVOIR           439
#define IDB_ICON_PM_DEOXYS              440
#define IDB_ICON_PM_RAYQUAZA            441
#define IDB_ICON_PM_VULPIX              442
#define IDB_ICON_PM_SMOOCHUM            443
#define IDB_PM_DEOXYS_FRONT             444
#define IDB_JUMP_SAND1                  445
#define IDB_DOUCHITOWN_HOUSE2           446
#define IDB_JUMP_SAND2                  447
#define IDB_BITMAP22                    448
#define IDB_JUMP_SAND3                  448
#define IDB_RTSEA1_1                    449
#define IDB_RTSEA1_2                    450
#define IDB_RTSEA2_1                    451
#define IDB_RTSEA2_2                    452
#define IDB_RTSEA2_3                    453
#define IDB_RTSEA2_4                    454
#define IDB_RTSEA2_5                    455
#define IDB_RTSEA2_6                    456
#define IDB_RTSEA1_3                    457
#define IDB_RTSEA1_4                    458
#define IDB_RTSEA1_5                    459
#define IDB_RTSEA1_6                    460
#define IDB_LAKE_102                    461
#define IDB_LAND_C                      462
#define IDB_LAND_T                      463
#define IDB_LAND_R                      464
#define IDB_LAND_L                      465
#define IDB_LAND_B                      466
#define IDB_LAND_RT                     467
#define IDB_LAND_RB                     468
#define IDB_LAND_LT                     469
#define IDB_LAND_LB                     470
#define IDB_TIANYUAN_GYM                471
#define IDB_TIANYUAN_LLAKE4             472
#define IDB_TIANYUAN_LLAKE3             473
#define IDB_TIANYUAN_LLAKE2             474
#define IDB_TIANYUAN_LLAKE1             475
#define IDB_TIANYUAN_LTHOUSE            476
#define IDB_TIANYUAN_NHOUSE             477
#define IDB_TIANYUAN_RBHOUSE            478
#define IDB_TIANYUAN_RTLAKE             479
#define IDB_SKILL_CONFUSION7            480
#define IDB_SKILL_CONFUSION3            481
#define IDB_SKILL_CONFUSION4            482
#define IDB_SKILL_CONFUSION5            483
#define IDB_SKILL_CONFUSION2            484
#define IDB_SKILL_CONFUSION6            485
#define IDB_SKILL_CONFUSION1            486
#define IDB_SKILL_METALCLAW9            487
#define IDB_SKILL_METALCLAW10           488
#define IDB_SKILL_METALCLAW8            489
#define IDB_SKILL_METALCLAW7            490
#define IDB_SKILL_METALCLAW6            491
#define IDB_SKILL_METALCLAW3            492
#define IDB_SKILL_METALCLAW4            493
#define IDB_SKILL_METALCLAW5            494
#define IDB_SKILL_METALCLAW2            495
#define IDB_SKILL_METALCLAW1            496
#define IDB_SKILL_SCARYFACE2            497
#define IDB_SKILL_SCARYFACE3            498
#define IDB_SKILL_SCARYFACE1            499
#define IDB_SKILL_LICK3                 500
#define IDB_SKILL_LICK4                 501
#define IDB_SKILL_LICK2                 502
#define IDB_SKILL_LICK1                 503
#define IDB_ENEMY_SKILL_POWDERSNOW21    506
#define IDB_ENEMY_SKILL_POWDERSNOW18    507
#define IDB_ENEMY_SKILL_POWDERSNOW19    508
#define IDB_ENEMY_SKILL_POWDERSNOW20    509
#define IDB_ENEMY_SKILL_POWDERSNOW17    510
#define IDB_ENEMY_SKILL_POWDERSNOW22    511
#define IDB_ENEMY_SKILL_POWDERSNOW16    512
#define IDB_ENEMY_SKILL_POWDERSNOW15    513
#define IDB_ENEMY_SKILL_POWDERSNOW14    514
#define IDB_ENEMY_SKILL_POWDERSNOW13    515
#define IDB_ENEMY_SKILL_POWDERSNOW12    516
#define IDB_ENEMY_SKILL_POWDERSNOW11    517
#define IDB_ENEMY_SKILL_POWDERSNOW10    518
#define IDB_ENEMY_SKILL_POWDERSNOW9     519
#define IDB_ENEMY_SKILL_POWDERSNOW8     520
#define IDB_ENEMY_SKILL_POWDERSNOW7     521
#define IDB_ENEMY_SKILL_POWDERSNOW6     522
#define IDB_ENEMY_SKILL_POWDERSNOW5     523
#define IDB_ENEMY_SKILL_POWDERSNOW4     524
#define IDB_ENEMY_SKILL_POWDERSNOW3     525
#define IDB_ENEMY_SKILL_POWDERSNOW2     526
#define IDB_ENEMY_SKILL_POWDERSNOW50    527
#define IDB_ENEMY_SKILL_POWDERSNOW1     527
#define IDB_SKILL_POWDERSNOW21          528
#define IDB_SKILL_POWDERSNOW20          529
#define IDB_SKILL_POWDERSNOW19          530
#define IDB_SKILL_POWDERSNOW18          531
#define IDB_SKILL_POWDERSNOW17          532
#define IDB_SKILL_POWDERSNOW16          533
#define IDB_SKILL_POWDERSNOW15          534
#define IDB_SKILL_POWDERSNOW14          535
#define IDB_SKILL_POWDERSNOW13          536
#define IDB_SKILL_POWDERSNOW12          537
#define IDB_SKILL_POWDERSNOW11          538
#define IDB_SKILL_POWDERSNOW10          539
#define IDB_SKILL_POWDERSNOW9           540
#define IDB_SKILL_POWDERSNOW8           541
#define IDB_SKILL_POWDERSNOW7           542
#define IDB_SKILL_POWDERSNOW6           543
#define IDB_SKILL_POWDERSNOW5           544
#define IDB_SKILL_POWDERSNOW4           545
#define IDB_SKILL_POWDERSNOW3           546
#define IDB_SKILL_POWDERSNOW2           547
#define IDB_SKILL_POWDERSNOW1           548
#define IDB_SKILL_POISONGAS5            549
#define IDB_SKILL_POISONGAS4            550
#define IDB_SKILL_POISONGAS3            551
#define IDB_SKILL_POISONGAS2            552
#define IDB_SKILL_POISONGAS1            553
#define IDB_ENEMY_SKILL_SLUDGE15        554
#define IDB_ENEMY_SKILL_SLUDGE14        555
#define IDB_ENEMY_SKILL_SLUDGE13        556
#define IDB_ENEMY_SKILL_SLUDGE12        557
#define IDB_ENEMY_SKILL_SLUDGE11        558
#define IDB_SKILL_SLUDGE15              559
#define IDB_SKILL_SLUDGE14              560
#define IDB_SKILL_SLUDGE13              561
#define IDB_SKILL_SLUDGE12              562
#define IDB_SKILL_SLUDGE11              563
#define IDB_ENEMY_SKILL_SLUDGE1         564
#define IDB_SKILL_SLUDGE10              565
#define IDB_ENEMY_SKILL_SLUDGE2         566
#define IDB_SKILL_SLUDGE9               567
#define IDB_ENEMY_SKILL_SLUDGE3         568
#define IDB_SKILL_SLUDGE8               569
#define IDB_ENEMY_SKILL_SLUDGE4         570
#define IDB_SKILL_SLUDGE7               571
#define IDB_ENEMY_SKILL_SLUDGE5         572
#define IDB_SKILL_SLUDGE6               573
#define IDB_ENEMY_SKILL_SLUDGE6         574
#define IDB_SKILL_SLUDGE5               575
#define IDB_ENEMY_SKILL_SLUDGE7         576
#define IDB_SKILL_SLUDGE4               577
#define IDB_ENEMY_SKILL_SLUDGE8         578
#define IDB_SKILL_SLUDGE3               579
#define IDB_ENEMY_SKILL_SLUDGE9         580
#define IDB_SKILL_SLUDGE2               581
#define IDB_ENEMY_SKILL_SLUDGE10        582
#define IDB_SKILL_SLUDGE1               583
#define IDB_ENEMY_SKILL_FLAMETHROWER8   584
#define IDB_ENEMY_SKILL_FLAMETHROWER7   585
#define IDB_ENEMY_SKILL_FLAMETHROWER6   586
#define IDB_ENEMY_SKILL_FLAMETHROWER5   587
#define IDB_ENEMY_SKILL_FLAMETHROWER4   588
#define IDB_ENEMY_SKILL_FLAMETHROWER3   589
#define IDB_ENEMY_SKILL_FLAMETHROWER2   590
#define IDB_ENEMY_SKILL_FLAMETHROWER1   591
#define IDB_SKILL_FLAMETHROWER6         592
#define IDB_SKILL_FLAMETHROWER10        593
#define IDB_SKILL_FLAMETHROWER9         594
#define IDB_SKILL_FLAMETHROWER8         595
#define IDB_SKILL_FLAMETHROWER7         596
#define IDB_SKILL_FLAMETHROWER4         597
#define IDB_SKILL_FLAMETHROWER2         598
#define IDB_SKILL_FLAMETHROWER5         599
#define IDB_SKILL_FLAMETHROWER11        600
#define IDB_SKILL_FLAMETHROWER3         601
#define IDB_SKILL_FLAMETHROWER1         602
#define IDB_SKILL_THUNDERSHOCK3         603
#define IDB_SKILL_THUNDERSHOCK8         604
#define IDB_SKILL_THUNDERSHOCK7         605
#define IDB_SKILL_THUNDERSHOCK6         606
#define IDB_SKILL_THUNDERSHOCK5         607
#define IDB_SKILL_THUNDERSHOCK4         608
#define IDB_SKILL_THUNDERSHOCK2         609
#define IDB_SKILL_THUNDERSHOCK1         610
#define IDB_SKILL_THUNDERBOLT1          611
#define IDB_SKILL_THUNDERBOLT2          612
#define IDB_SKILL_THUNDERBOLT3          613
#define IDB_SKILL_THUNDERBOLT4          614
#define IDB_SKILL_THUNDERBOLT5          615
#define IDB_SKILL_THUNDERBOLT6          616
#define IDB_SKILL_THUNDERBOLT7          617
#define IDB_SKILL_THUNDERBOLT8          618
#define IDB_SKILL_THUNDERBOLT9          619
#define IDB_ENEMY_SKILL_BUBBLEBEAM2     620
#define IDB_ENEMY_SKILL_BUBBLEBEAM3     621
#define IDB_ENEMY_SKILL_BUBBLEBEAM4     622
#define IDB_ENEMY_SKILL_BUBBLEBEAM5     623
#define IDB_ENEMY_SKILL_BUBBLEBEAM6     624
#define IDB_ENEMY_SKILL_BUBBLEBEAM7     625
#define IDB_ENEMY_SKILL_BUBBLEBEAM8     626
#define IDB_ENEMY_SKILL_BUBBLEBEAM9     627
#define IDB_ENEMY_SKILL_BUBBLEBEAM10    628
#define IDB_SKILL_BUBBLEBEAM1           629
#define IDB_SKILL_BUBBLEBEAM2           630
#define IDB_SKILL_BUBBLEBEAM3           631
#define IDB_SKILL_BUBBLEBEAM4           632
#define IDB_SKILL_BUBBLEBEAM5           633
#define IDB_SKILL_BUBBLEBEAM6           634
#define IDB_SKILL_BUBBLEBEAM7           635
#define IDB_SKILL_BUBBLEBEAM8           636
#define IDB_SKILL_BUBBLEBEAM9           637
#define IDB_SKILL_BUBBLEBEAM10          638
#define IDB_ENEMY_SKILL_BUBBLEBEAM1     639
#define IDB_ENEMY_SKILL_WATERGUN1       640
#define IDB_ENEMY_SKILL_WATERGUN2       641
#define IDB_ENEMY_SKILL_WATERGUN3       642
#define IDB_ENEMY_SKILL_WATERGUN4       643
#define IDB_ENEMY_SKILL_WATERGUN5       644
#define IDB_ENEMY_SKILL_WATERGUN6       645
#define IDB_ENEMY_SKILL_WATERGUN7       646
#define IDB_ENEMY_SKILL_WATERGUN8       647
#define IDB_ENEMY_SKILL_WATERGUN9       648
#define IDB_ENEMY_SKILL_WATERGUN10      649
#define IDB_SKILL_WATERGUN1             650
#define IDB_SKILL_WATERGUN2             651
#define IDB_SKILL_WATERGUN3             652
#define IDB_SKILL_WATERGUN4             653
#define IDB_SKILL_WATERGUN5             654
#define IDB_SKILL_WATERGUN6             655
#define IDB_SKILL_WATERGUN7             656
#define IDB_SKILL_WATERGUN8             657
#define IDB_SKILL_WATERGUN9             658
#define IDB_SKILL_WATERGUN10            659
#define IDB_SKILL_CRUNCH1               660
#define IDB_SKILL_CRUNCH2               661
#define IDB_SKILL_CRUNCH3               662
#define IDB_SKILL_CRUNCH4               663
#define IDB_SKILL_CRUNCH5               664
#define IDB_SKILL_CRUNCH6               665
#define IDB_SKILL_CRUNCH7               666
#define IDB_SKILL_LEAFBLADE1            667
#define IDB_SKILL_LEAFBLADE2            668
#define IDB_SKILL_LEAFBLADE3            669
#define IDB_SKILL_LEAFBLADE4            670
#define IDB_SKILL_LEAFBLADE5            671
#define IDB_SKILL_LEAFBLADE6            672
#define IDB_SKILL_AURORABEAM6           673
#define IDB_SKILL_AURORABEAM5           674
#define IDB_SKILL_AURORABEAM9           675
#define IDB_SKILL_AURORABEAM8           676
#define IDB_SKILL_AURORABEAM7           677
#define IDB_SKILL_AURORABEAM4           678
#define IDB_SKILL_AURORABEAM3           679
#define IDB_SKILL_AURORABEAM2           680
#define IDB_SKILL_AURORABEAM1           681
#define IDB_SKILL_LEAFSTORM11           682
#define IDB_SKILL_LEAFSTORM10           683
#define IDB_SKILL_LEAFSTORM9            684
#define IDB_SKILL_LEAFSTORM8            685
#define IDB_SKILL_LEAFSTORM7            686
#define IDB_SKILL_LEAFSTORM6            687
#define IDB_SKILL_LEAFSTORM5            688
#define IDB_SKILL_LEAFSTORM4            689
#define IDB_SKILL_LEAFSTORM3            690
#define IDB_SKILL_LEAFSTORM2            691
#define IDB_SKILL_LEAFSTORM1            692
#define IDB_SKILL_NIGHTSHADE4           693
#define IDB_SKILL_NIGHTSHADE5           694
#define IDB_SKILL_NIGHTSHADE3           695
#define IDB_SKILL_NIGHTSHADE6           696
#define IDB_SKILL_NIGHTSHADE2           697
#define IDB_SKILL_NIGHTSHADE7           698
#define IDB_SKILL_NIGHTSHADE1           699
#define IDB_SKILL_PHYCHOBOOST27         700
#define IDB_SKILL_PHYCHOBOOST26         701
#define IDB_SKILL_PHYCHOBOOST25         702
#define IDB_SKILL_PHYCHOBOOST24         703
#define IDB_SKILL_PHYCHOBOOST23         704
#define IDB_SKILL_PHYCHOBOOST22         705
#define IDB_SKILL_PHYCHOBOOST21         706
#define IDB_SKILL_PHYCHOBOOST20         707
#define IDB_SKILL_PHYCHOBOOST19         708
#define IDB_SKILL_PHYCHOBOOST18         709
#define IDB_SKILL_PHYCHOBOOST17         710
#define IDB_SKILL_PHYCHOBOOST16         711
#define IDB_SKILL_PHYCHOBOOST15         712
#define IDB_SKILL_PHYCHOBOOST14         713
#define IDB_SKILL_PHYCHOBOOST13         714
#define IDB_SKILL_PHYCHOBOOST12         715
#define IDB_SKILL_PHYCHOBOOST11         716
#define IDB_SKILL_PHYCHOBOOST10         717
#define IDB_SKILL_PHYCHOBOOST9          718
#define IDB_SKILL_PHYCHOBOOST8          719
#define IDB_SKILL_PHYCHOBOOST7          720
#define IDB_SKILL_PHYCHOBOOST6          721
#define IDB_SKILL_PHYCHOBOOST5          722
#define IDB_SKILL_PHYCHOBOOST4          723
#define IDB_SKILL_PHYCHOBOOST3          724
#define IDB_SKILL_PHYCHOBOOST2          725
#define IDB_SKILL_PHYCHOBOOST1          726
#define IDB_ENEMY_SKILL_PHYCHOBOOST19   727
#define IDB_ENEMY_SKILL_PHYCHOBOOST15   728
#define IDB_ENEMY_SKILL_PHYCHOBOOST14   729
#define IDB_ENEMY_SKILL_PHYCHOBOOST17   730
#define IDB_ENEMY_SKILL_PHYCHOBOOST18   731
#define IDB_ENEMY_SKILL_PHYCHOBOOST26   732
#define IDB_ENEMY_SKILL_PHYCHOBOOST20   733
#define IDB_ENEMY_SKILL_PHYCHOBOOST25   734
#define IDB_ENEMY_SKILL_PHYCHOBOOST27   735
#define IDB_ENEMY_SKILL_PHYCHOBOOST23   736
#define IDB_ENEMY_SKILL_PHYCHOBOOST22   737
#define IDB_ENEMY_SKILL_PHYCHOBOOST16   738
#define IDB_ENEMY_SKILL_PHYCHOBOOST24   739
#define IDB_ENEMY_SKILL_PHYCHOBOOST21   740
#define IDB_ENEMY_SKILL_PHYCHOBOOST13   741
#define IDB_ENEMY_SKILL_PHYCHOBOOST3    742
#define IDB_ENEMY_SKILL_PHYCHOBOOST11   743
#define IDB_ENEMY_SKILL_PHYCHOBOOST7    744
#define IDB_ENEMY_SKILL_PHYCHOBOOST8    745
#define IDB_ENEMY_SKILL_PHYCHOBOOST10   746
#define IDB_ENEMY_SKILL_PHYCHOBOOST9    747
#define IDB_ENEMY_SKILL_PHYCHOBOOST5    748
#define IDB_ENEMY_SKILL_PHYCHOBOOST2    749
#define IDB_ENEMY_SKILL_PHYCHOBOOST1    750
#define IDB_ENEMY_SKILL_PHYCHOBOOST4    751
#define IDB_ENEMY_SKILL_PHYCHOBOOST12   752
#define IDB_BITMAP47                    753
#define IDB_ENEMY_SKILL_PHYCHOBOOST6    753
#define IDB_SKILL_SWIFT8                754
#define IDB_SKILL_SWIFT7                755
#define IDB_SKILL_SWIFT6                756
#define IDB_SKILL_SWIFT5                757
#define IDB_SKILL_SWIFT4                758
#define IDB_SKILL_SWIFT3                759
#define IDB_SKILL_SWIFT2                760
#define IDB_SKILL_SWIFT1                761
#define IDB_ENEMY_SKILL_HYPERBEAM3      762
#define IDB_ENEMY_SKILL_HYPERBEAM15     763
#define IDB_ENEMY_SKILL_HYPERBEAM1      764
#define IDB_ENEMY_SKILL_HYPERBEAM5      765
#define IDB_ENEMY_SKILL_HYPERBEAM6      766
#define IDB_ENEMY_SKILL_HYPERBEAM9      767
#define IDB_ENEMY_SKILL_HYPERBEAM14     768
#define IDB_ENEMY_SKILL_HYPERBEAM10     769
#define IDB_ENEMY_SKILL_HYPERBEAM13     770
#define IDB_ENEMY_SKILL_HYPERBEAM4      771
#define IDB_ENEMY_SKILL_HYPERBEAM7      772
#define IDB_ENEMY_SKILL_HYPERBEAM12     773
#define IDB_ENEMY_SKILL_HYPERBEAM8      774
#define IDB_ENEMY_SKILL_HYPERBEAM2      775
#define IDB_ENEMY_SKILL_HYPERBEAM11     776
#define IDB_SKILL_HYPERBEAM15           777
#define IDB_SKILL_HYPERBEAM14           778
#define IDB_SKILL_HYPERBEAM13           779
#define IDB_SKILL_HYPERBEAM12           780
#define IDB_SKILL_HYPERBEAM11           781
#define IDB_SKILL_HYPERBEAM10           782
#define IDB_SKILL_HYPERBEAM9            783
#define IDB_SKILL_HYPERBEAM8            784
#define IDB_SKILL_HYPERBEAM7            785
#define IDB_SKILL_HYPERBEAM6            786
#define IDB_SKILL_HYPERBEAM5            787
#define IDB_SKILL_HYPERBEAM4            788
#define IDB_SKILL_HYPERBEAM3            789
#define IDB_SKILL_HYPERBEAM2            790
#define IDB_BITMAP51                    791
#define IDB_SKILL_HYPERBEAM1            791
#define IDB_FREEZE_ICON                 792
#define IDB_PARALYSIS_ICON              793
#define IDB_POISON_ICON                 794
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        795
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
