//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 產生的 Include 檔案。
// 由 game.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_RACKET                      131
#define IDB_BITMAP1                     132
#define IDB_BALL1                       134
#define IDB_BALL2                       135
#define IDB_BALL3                       136
#define IDB_BALL4                       137
#define IDB_0                           138
#define IDB_1                           139
#define IDB_100                         139
#define IDB_2                           140
#define IDB_3                           141
#define IDB_4                           142
#define IDB_5                           143
#define IDB_6                           144
#define IDB_7                           145
#define IDB_8                           146
#define IDB_9                           147
#define IDB_MINUS                       148
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_BITMAP2                     156
#define IDB_LOADING                     156
#define IDB_WEIBAITOWN                  166
#define IDB_BILLBOARD                   167
#define IDB_GRASS_LAND                  168
#define IDB_GREEN_FLOWER                169
#define IDB_GREEN_GRASS                 170
#define IDB_GREEN_TREE                  171
#define IDB_WEIBAITOWN_HOUSE1           172
#define IDB_WEIBAITOWN_HOUSE2           173
#define IDB_BITMAP10                    174
#define IDB_WEIBAITOWN_PRO_HOUSE        174
#define HERO_BACK                       176
#define HERO_BACK_ONE                   177
#define HERO_BACK_TWO                   178
#define HERO_FRONT                      179
#define HERO_FRONT_ONE                  180
#define HERO_FRONT_TWO                  181
#define HERO_LEFT                       182
#define IDB_BITMAP11                    183
#define HERO_LEFT_ONE                   183
#define HERO_RIGHT                      185
#define HERO_RIGHT_ONE                  186
#define HERO_RIGHT_TWO                  187
#define IDB_WEIBAITOWN_HOUSE1_1F        188
#define IDB_WEIBAITOWN_HOUSE2_1F        189
#define IDB_WEIBAITOWN_PRO_HOUSE_INSIDE 190
#define IDB_WEIBAITOWN_HOUSE1_2F        191
#define IDB_BITMAP4                     192
#define IDB_WEIBAITOWN_HOUSE2_2F        192
#define MOM_UP                          193
#define MOM_LEFT                        194
#define MOM_RIGHT                       195
#define HOME                            196
#define HOME_LOG                        197
#define MOM_DOWN                        198
#define NORMAL_DIALOG_SCREEN            199
#define TEXT_CURSOR2                    200
#define TEXT_CURSOR1                    201
#define TEXT_CURSOR3                    202
#define SYSTEM_DIALOG_SCREEN            203
#define IDB_BITMAP3                     204
#define HOME_LOG_BLANK                  204
#define IDB_ALPHABET_SMALL_A            205
#define IDB_ALPHABET_SMALL_B            206
#define IDB_ALPHABET_SMALL_C            207
#define IDB_ALPHABET_SMALL_D            208
#define IDB_ALPHABET_SMALL_E            210
#define IDB_ALPHABET_SMALL_F            211
#define IDB_ALPHABET_SMALL_G            212
#define IDB_ALPHABET_SMALL_H            213
#define IDB_ALPHABET_SMALL_I            214
#define IDB_ALPHABET_SMALL_J            215
#define IDB_TEXT_SPACE                  216
#define IDB_ALPHABET_SMALL_K            217
#define IDB_ALPHABET_SMALL_L            218
#define IDB_ALPHABET_SMALL_O            219
#define IDB_ALPHABET_SMALL_Q            220
#define IDB_ALPHABET_SMALL_S            221
#define IDB_ALPHABET_SMALL_M            222
#define IDB_ALPHABET_SMALL_T            223
#define IDB_ALPHABET_SMALL_V            224
#define IDB_ALPHABET_SMALL_W            225
#define IDB_ALPHABET_SMALL_X            227
#define IDB_ALPHABET_SMALL_N            228
#define IDB_ALPHABET_SMALL_P            229
#define IDB_ALPHABET_SMALL_R            230
#define IDB_ALPHABET_SMALL_U            231
#define IDB_ALPHABET_SMALL_Y            232
#define IDB_ALPHABET_SMALL_Z            233
#define IDB_JUMP_LAND                   234
#define HERO_LEFT_TWO                   235
#define FATGUY_LEFT                     237
#define FATGUY_RIGHT                    238
#define LITTLE_GIRL_FRONT               239
#define FATGUY_BACK                     240
#define IDB_BITMAP9                     241
#define FATGUY_FRONT                    241
#define IDB_BATTLE_BACKGROUND           242
#define IDB_BATTLE_GROUND               243
#define IDB_BATTLE_HERO                 244
#define IDB_BATTLE_OPTION               245
#define IDB_BLACK                       246
#define IDB_ENEMY_BAR                   247
#define IDB_HP_GREEN                    248
#define IDB_HP_RED                      249
#define IDB_HP_YELLOW                   250
#define IDB_MY_BAR                      251
#define IDB_SKILL_IMPACT1               252
#define IDB_SKILL_IMPACT2               253
#define IDB_SKILL_OPTION                254
#define IDB_PM_TREECKO_BACK             255
#define IDB_PM_TREECKO_FRONT            256
#define IDB_CURSOR                      257
#define IDB_BATTLE_DIALOG               258
#define IDB_M_GREEN_GRASS               259
#define IDB_ALPHABET_SPACE              260
#define IDB_ALPHABET_DOT                261
#define IDB_ALPHABET_END                262
#define IDB_BITMAP6                     263
#define BG_BACKPACK                     263
#define IDB_PICKABLE_OBJECT             264
#define BG_SELF                         266
#define BG_BACKPACK_CURSOR1             267
#define BG_BACKPACK_CURSOR2             268
#define BG_BACKPACK_CURSOR3             269
#define BG_BACKPACK_FLAG                270
#define IDB_ANTIDOTE                    272
#define ITEM_ANTIDOTE                   272
#define BG_BACKPACK_ITEMCURSOR          273
#define BG_BACKPACK_BACK                274
#define IDB_MENU_BOTTOM                 275
#define IDB_MENU_MIDDLE                 276
#define IDB_MENU_TOP                    277
#define IDB_POKEMON_OPERATION_PANEL     278
#define IDB_POKEMON_BAR_UNSELECTED      279
#define IDB_BITMAP16                    281
#define IDB_POKEMON_BAR_FIRST_UNSELECTED 281
#define IDB_POKEMON_BAR_SELECTED        282
#define IDB_POKEMON_SELECT_PANEL        283
#define IDB_EXPBAR                      284
#define IDB_PM_ABILITY                  285
#define IDB_PM_SKILL_PANEL              286
#define IDB_POKEMON_BAR_FIRST_SELECT    287
#define IDB_POKEMON_BAR_SELECT          288
#define IDB_BITMAP7                     289
#define IDB_SKILL_SELECT                290
#define IDB_SKILL_SIDEBAR               291
#define IDB_BITMAP8                     292
#define IDB_SKILL_LIST                  292
#define BG_YESNO                        293
#define IDB_ICON_PM_TREECKO             294
#define BAG_PANEL                       295
#define BG_PANEL                        295
#define IDB_QUESTION_MARK               297
#define IDB_BITMAP12                    298
#define IDB_BITMAP13                    299
#define BG_ITEMAMOUNT                   299
#define IDB_BITMAP14                    300
#define IDB_BITMAP15                    301
#define IDB_HOSPITAL                    302
#define IDB_ALPHABET_DIVISION           303
#define IDB_NORMAL_HOUSE1               304
#define IDB_STORE                       305
#define IDB_LV_UP_PANEL                 306
#define IDB_LV_UP_FPANEL                307
#define IDB_BITMAP17                    308
#define IDB_HOSPITAL_INSIDE             308
#define HEAL_BALL1                      309
#define HEAL_BALL2                      310
#define HEAL_BALL3                      311
#define HEAL_BALL4                      312
#define HEAL_BALL5                      313
#define HEAL_BALL6                      314
#define HEAL_BALL7                      315
#define HEAL_BALL8                      316
#define HEAL_BALL9                      317
#define HEAL_BALL10                     318
#define HEAL_BALL11                     319
#define HEAL_BALL12                     320
#define IDB_ICON_PM_JIRACHI             321
#define IDB_PM_JIRACHI_BACK             322
#define IDB_PM_JIRACHI_FRONT            323
#define IDB_SKILL_LEER1                 324
#define IDB_SKILL_LEER2                 325
#define IDB_SKILL_LEER3                 326
#define IDB_SKILL_LEER4                 327
#define IDB_BITMAP22                    328
#define IDB_SKILL_LEER5                 328
#define IDB_SHOP_MAP                    329
#define ITEM_FIGHTERGLOVE               330
#define ITEM_VULNERARY                  331
#define TRADEMODE_SELECT                332
#define SHOP_BLANK_PANEL                333
#define SHOP_DESCRIPTION_PANEL          334
#define SHOP_IMAGE_PANEL                335
#define SHOP_ITEMLIST_PANEL             336
#define SHOP_MONEY_PANEL                337
#define IDB_BITMAP18                    339
#define IDB_USEITEM_PANEL               340
#define IDB_GIVEITEM_PANEL              341
#define IDB_BITMAP19                    343
#define IDB_BLANK_PANEL                 343
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        344
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
